strategy:
  bb_period: 20
  bb_std: 2
  ma_long: 20
  ma_short: 10
  max_position: 5
  position_size: 0.2
  rsi_overbought: 70
  rsi_oversold: 30
  rsi_period: 14
  stop_loss: 0.03
  take_profit: 0.05
interval: 4
